spring:
  data:
    mongodb:
      uri: mongodb+srv://animekartcoin_db_user:TZxw7PsO1a9jHcuB@cluster0.kx66lrb.mongodb.net/?appName=Cluster0
      database: animekartcoin_db
  application:
    name: ecommerce-backend

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds

# Logging
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.ecommerce: DEBUG
